# Generated by Django 3.2.12 on 2022-08-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('name', models.CharField(max_length=50, verbose_name='نام تیم')),
                ('logo', models.ImageField(blank=True, help_text='لطفا تصویری با طول x و عرض y بارگزاری کنید.', null=True, upload_to='teams/', verbose_name='لوگوی تیم')),
            ],
            options={
                'verbose_name': 'تیم',
                'verbose_name_plural': 'تیم',
            },
        ),
    ]
