# Generated by Django 3.2.12 on 2022-08-15 22:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import events.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('event_time', django_jalali.db.models.jDateTimeField(null=True, verbose_name='زمان برگزاری')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات رویداد')),
                ('image', models.ImageField(blank=True, default='events/default.jpg', help_text='لطفا تصویری با عرض y و ارتفاع x پیکسل بارگذاری نمایید.', null=True, upload_to='events', verbose_name='تصویر رویداد')),
                ('total_capacity', models.PositiveIntegerField(verbose_name='ظرفیت کل')),
                ('remaining_capacity', models.PositiveIntegerField(verbose_name='ظرفیت باقیمانده')),
                ('price', models.PositiveIntegerField(default=0, help_text='قیمت به تومان', verbose_name='قیمت')),
                ('is_available', models.BooleanField(default=True, help_text='زمانی که ظرفیت رویداد به پایان برسد یا ادمین سایت این گزینه را لغو کند، امکان خرید بلیط برای این رویداد غیرفعال خواهد شد.', verbose_name='قابل استفاده بودن')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_team_set', to='teams.team', verbose_name='تیم مهمان')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_team_set', to='teams.team', verbose_name='تیم میزبان')),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویداد',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('full_name', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='لطفا از کیبورد فارسی استفاده کنید.', regex='^[\u0600-ۿ\\s]+$')], verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='شماره موبایل معتبر نمیباشد!', regex='^(0)?9\\d{9}$')], verbose_name='شماره موبایل')),
                ('national_code', models.CharField(max_length=10, validators=[events.validators.validate_iran_national_code], verbose_name='کدملی')),
                ('is_used', models.BooleanField(default=False, help_text='زمانی که بلیط تحویل ورزشگاه شد، این فیلد باید توسط ادمین تغییر کند.', verbose_name='استفاده شده')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='رویداد')),
            ],
            options={
                'verbose_name': 'بلیط',
                'verbose_name_plural': 'بلیط',
                'unique_together': {('event', 'national_code')},
            },
        ),
    ]
