# Generated by Django 3.2.15 on 2022-08-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(1, 'در انتظار'), (2, 'موفق'), (3, 'ناموفق')], default=1, verbose_name='وضعیت'),
        ),
    ]
