# Generated by Django 3.2.15 on 2022-08-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='tickets', verbose_name='کد QR'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
    ]
