# Generated by Django 3.2.15 on 2022-08-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='bank_record',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره رکورد بانک'),
        ),
    ]
