# Generated by Django 3.2.15 on 2022-08-17 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_ticket_bank_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='bank_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='azbankgateways.bank', verbose_name='ثبت بانک'),
        ),
    ]
