# Generated by Django 3.2.15 on 2022-08-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_ticket_bank_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='bank_record',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره رکورد بانک'),
        ),
    ]
