# Generated by Django 3.2.15 on 2022-08-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_ticket_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='unique_code',
            field=models.CharField(default=1, max_length=230, verbose_name='کد یکتا'),
            preserve_default=False,
        ),
    ]
