# Generated by Django 3.2.15 on 2022-08-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_ticket_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='national_code',
            field=models.CharField(max_length=10, verbose_name='کدملی'),
        ),
    ]
