# Generated by Django 3.2.12 on 2022-08-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_banner', models.ImageField(blank=True, help_text='لطفا تصویری با عرض ۱۹۲۰ و ارتفاع ۸۱۰ پیکسل بارگذاری نمایید.', null=True, upload_to='site_settings', verbose_name='بنر صفحه اصلی')),
                ('home_link', models.URLField(blank=True, default='belitmes.ir', null=True, verbose_name='لینک صفحه اصلی')),
                ('kavenegar_api_key', models.CharField(blank=True, max_length=150, null=True, verbose_name='کد API key کاوه نگار')),
                ('kavenegar_sender', models.CharField(blank=True, max_length=150, null=True, verbose_name='فرستنده پیامک کاوه نگار')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
