# Generated by Django 3.2.13 on 2022-05-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='نام ')),
                ('pic', models.ImageField(upload_to='players/', verbose_name='عکس ')),
                ('number', models.SmallIntegerField(verbose_name='شماره ')),
                ('post', models.CharField(max_length=30, verbose_name='پست ')),
                ('age', models.SmallIntegerField(verbose_name='سن ')),
                ('goal', models.SmallIntegerField(verbose_name=' گل زده ')),
            ],
        ),
    ]
