# Generated by Django 3.2.13 on 2022-05-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20220515_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('-goal',)},
        ),
    ]
